# To be run preferably in batch, without graphics:
# % ComptonSims -m batch.mac
#
#/run/numberOfWorkers 4

/run/initialize
#/run/geometryModified
#
# Run for different energies
/gun/particle gamma
/gun/energy 1 MeV
#
/ComptonDetector/setArmAngle {angle} deg
/ComptonDetector/update
/ComptonDetector/printInfo
/analysis/setFileName 92916_{angle}deg
/analysis/setHistoDirName angleStudies_hist
/analysis/setNtupleDirName angleStudies_ntuple
/run/printProgress 100000
/run/beamOn 20000000

